{{- if .Values.payment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    {{- include "finhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-payment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-payment
    spec:
      initContainers:
        - name: wait-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - until pg_isready -h {{ .Release.Name }}-postgres -p {{ .Values.infrastructure.postgres.port }}; do echo "Waiting for PostgreSQL..."; sleep 2; done
        - name: wait-kafka
          image: busybox:1.36
          command: ["/bin/sh", "-c", "echo 'Waiting for Kafka 40s...'; sleep 40; echo 'Done'"]
        - name: wait-eureka
          image: busybox:1.36
          command:
            - sh
            - -c
            - until wget -qO- http://{{ .Release.Name }}-eureka:{{ .Values.eureka.port }}/actuator/health 2>/dev/null | grep -q UP; do echo "Waiting for Eureka..."; sleep 3; done
      containers:
        - name: payment
          image: "{{ .Values.payment.image }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.payment.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.payment.db }}"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            {{- toYaml .Values.payment.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    {{- include "finhub.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-payment
  ports:
    - port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.port }}
{{- end }}
