apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "finhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
